version: '3.8'

services:
  cyndaquil-users:
    build:
      context: .
      dockerfile: ./Dockerfile
    expose: 
      - 8080
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=production
      - PORT=8080
    image: cyndaquil-users:latest
    networks:
      - hoennetwork

  mysql:
    image: mysql:5.7.41
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=examplepassword
      - MYSQL_DATABASE=users
      - 


networks:
  hoennetwork:
    

