version: '3.8'

services:
  cyndaquil:
    image: cyndaquil-users-service:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    expose:
      - "8080"
    ports:
      - '8080:8080'
    env_file: .env
    environment:
      - NODE_ENV=production
      - PORT=8080
      - MYSQL_ROOT_PASSWORD=examplepassword
      - MYSQL_DATABASE=users
    depends_on:
      - mysql_db
    networks:
      - hoennetwork
  mysql_db:
    platform: linux/x86_64
    image: mysql:5.7
    restart: on-failure
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=examplepassword
      - MYSQL_DATABASE=users
    ports:
      - '3307:3306'
    volumes: 
      - db-config:/etc/mysql 
      - db-data:/var/lib/mysql 
    networks:
        - hoennetwork
networks:
  hoennetwork:

volumes:
  db-config:
  db-data:
    

