version: '3.8'

services:
  cyndaquil-users:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=production
      - PORT=8080
    image: cyndaquil-users:latest
    depends_on:
      - mysql_db
    networks:
      - hoennetwork
  mysql_db:
    platform: linux/x86_64
    image: mysql:5.7
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=examplepassword
      - MYSQL_DATABASE=users
      - MYSQL_USER=cyndaquil-api
      - MYSQL_PASSWORD=cyndaquilapi-example-auth-token-x
    ports:
      - '3307:3306'
    volumes: 
      - db-config:/etc/mysql 
      - db-data:/var/lib/mysql 
    networks:
        - hoennetwork
networks:
  hoennetwork:

volumes:
  db-config:
  db-data:
    

